_BASE_: "../Base-bagtricks.yml"

MODEL:
  CENTERPATH: "/home/baiyan/bct/bct_yan/logs/all_market1501/bagtricks_R50-softmax/all-center-bn.pkl" 
  BACKBONE:
    DEPTH: "50x" 
    PRETRAIN_PATH: "/home/baiyan/.cache/torch/checkpoints/resnet50-19c8e357.pth" 
    FEAT_DIM: 2048
  HEADS:
    NUM_CLASSES: 751 
  LOSSES:
    NAME: ("CrossEntropyLoss",) 
  WEIGHTS: "/home/baiyan/bct/bct_yan/logs/all_market1501/bagtricks_R50-softmax/model_final.pth" 
DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)

OUTPUT_DIR: "logs/"

SOLVER:
  IMS_PER_BATCH: 64
  CHECKPOINT_PERIOD: 10
  MAX_EPOCH: 120
TEST:
  EVAL_PERIOD: 10
  IMS_PER_BATCH: 64 
