_BASE_: "../Base-bagtricks.yml"

  
OLDMODEL:
  CONFIG: "/home/baiyan/bct/bct_yan/configs/Market1501/bagtricks_R50.yml"
  WEIGHT: "/home/baiyan/bct/bct_yan/logs/all_market1501/bagtricks_R50-softmax/model_final.pth" 
  N2OMAP: "n2o.npy"
MODEL:
  CENTERPATH: "/home/baiyan/bct/bct_yan/logs/all_market1501/bagtricks_R50-softmax/all-center-bn.pkl" 
  META_ARCHITECTURE: "DualTuning"
  BACKBONE:
    NAME: "build_resnet_backbone"
    DEPTH: "18x"
    PRETRAIN_PATH: "/home/baiyan/.cache/torch/checkpoints/resnet18-5c106cde.pth"
    FEAT_DIM: 512  
  LOSSES:
    NAME: ("CrossEntropyLoss", "OldCenterLoss_bn",) 
    # The loss include metric loss for target task and compatible loss. 
    # The metric loss can be one loss or a combination of multiple losses (e.g., "CrossEntropyLoss", "TripletLoss", "CircleLoss") 
    # The compatible loss can be one loss or a combination of multiple losses (e.g., "OldCenterLoss", "OldCenterLoss_bn", "loss_O2Nfc", "loss_N2Ofc", "N2OTripletLoss", "N2OTripletLoss_bn", "loss_KL", "loss_triplet_center","L2Loss").
    # More details see ./fastreid/modeling/meta_arch/dualtuning.py
    N2O:
      SCALE: 0.2

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)

OUTPUT_DIR: "logs/Market1501/R18-R50-softmax_n512_o2048_CenterBN" 
SOLVER:
  IMS_PER_BATCH: 64
  CHECKPOINT_PERIOD: 40

TEST:
  EVAL_PERIOD: 10
  IMS_PER_BATCH: 128
