_BASE_: "../Base-bagtricks.yml"

MODEL:
  CENTERPATH: "./logs/msmt17/bagtricks_R50_softmax_all_2/all-center-market_103_test2.pkl"
  BACKBONE:
    DEPTH: "50x" 
    PRETRAIN_PATH: "/home/baiyan/.cache/torch/checkpoints/resnet50-19c8e357.pth" 
    FEAT_DIM: 2048 
  HEADS:
    NUM_CLASSES: 4101 
  LOSSES:
    NAME: ("CrossEntropyLoss",) 
  WEIGHTS: "./logs/msmt17/bagtricks_R50_softmax_all_2/model_0103.pth"
DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)

OUTPUT_DIR: "logs/msmt17/bagtricks_R50_softmax_all_2"

SOLVER:
  IMS_PER_BATCH: 64
  CHECKPOINT_PERIOD: 10
  MAX_EPOCH: 120
TEST:
  EVAL_PERIOD: 10
  IMS_PER_BATCH: 128
