_BASE_: "../Base-bagtricks.yml"

MODEL:
  CENTERPATH: "./logs/dukemtmc/bagtricks_R50_softmax/all-center-dukemtmc.pkl"
  BACKBONE:
    DEPTH: "50x" 
    PRETRAIN_PATH: "/home/baiyan/.cache/torch/checkpoints/resnet50-19c8e357.pth" 
    FEAT_DIM: 2048 
  HEADS:
    NUM_CLASSES: 702 
  LOSSES:
    NAME: ("CrossEntropyLoss",) 
  WEIGHTS: "./logs/dukemtmc/bagtricks_R50_softmax/model_final.pth"
DATASETS:
  NAMES: ("DukeMTMC",)
  TESTS: ("DukeMTMC",)

OUTPUT_DIR: "logs/dukemtmc/bagtricks_R50_softmax/"

SOLVER:
  IMS_PER_BATCH: 64
  CHECKPOINT_PERIOD: 10
  MAX_EPOCH: 120
TEST:
  EVAL_PERIOD: 10
  IMS_PER_BATCH: 128
