_BASE_: "../Base-bagtricks.yml"
  
OLDMODEL:
  CONFIG: "./configs/MSMT17/bagtricks_R50.yml"
  WEIGHT: "./logs/msmt17/bagtricks_R50_softmax_all_2/model_0103.pth"
  N2OMAP: ""
MODEL:
  CENTERPATH: "./logs/msmt17/bagtricks_R50_softmax_all_2/all-center-market_103.pkl" 
  META_ARCHITECTURE: "DualTuning"
  BACKBONE:
    NAME: "build_resnet_backbone"
    DEPTH: "50x"
    PRETRAIN_PATH: "/home/baiyan/.cache/torch/checkpoints/resnet50-19c8e357.pth"
    FEAT_DIM: 2048
  LOSSES:
    NAME: ("CrossEntropyLoss","OldCenterLoss",) #"loss_O2Nfc", "loss_N2Ofc",) 
    # The loss include metric loss for target task and compatible loss. 
    # The metric loss can be one loss or a combination of multiple losses (e.g., "CrossEntropyLoss", "TripletLoss", "CircleLoss") 
    # The compatible loss can be one loss or a combination of multiple losses (e.g., "OldCenterLoss", "loss_O2Nfc", "loss_N2Ofc", "N2OTripletLoss", "N2OTripletLoss_bn", "loss_KL", "loss_triplet_center","L2Loss").
    # More details see ./fastreid/modeling/meta_arch/dualtuning.py
    N2OTRI:
       TWOWAY: True
    N2O:
      SCALE: 0.2

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)
BCT:
  FILTER_TEACHER: TRUE     
OUTPUT_DIR: "logs/MSMT17toMarket/R50-softmax_n2048_o2048_centerbn_0103" 
SOLVER:
  IMS_PER_BATCH: 64
  CHECKPOINT_PERIOD: 40

TEST:
  EVAL_PERIOD: 10
  IMS_PER_BATCH: 128
