_BASE_: "../Base-bagtricks.yml"

  
OLDMODEL:
  CONFIG: "./configs/MSMT17/part-bagtricks_R18-softmax.yml"
  WEIGHT: "./logs/part_msmt17/bagtricks_R18-softmax/model_final.pth"
  N2OMAP: "./datasets/N2O_label/msmt_n2o.npy"
MODEL:
  CENTERPATH: "./logs/part_msmt17/bagtricks_R18-softmax/all-center-bnfeat.pkl" 
  META_ARCHITECTURE: "Openbct"
  BACKBONE:
    NAME: "build_resnet_backbone"
    DEPTH: "18x"
    PRETRAIN_PATH: "/home/baiyan/.cache/torch/checkpoints/resnet18-5c106cde.pth"
    FEAT_DIM: 512
  LOSSES:
    NAME: ("CrossEntropyLoss", "OldCenterLoss", "loss_O2Nfc", "loss_N2Ofc",) 
    # The loss include metric loss for target task and compatible loss. 
    # The metric loss can be one loss or a combination of multiple losses (e.g., "CrossEntropyLoss", "TripletLoss", "CircleLoss") 
    # The compatible loss can be one loss or a combination of multiple losses (e.g., "OldCenterLoss", "loss_O2Nfc", "loss_N2Ofc", "N2OTripletLoss", "N2OTripletLoss_bn", "loss_KL", "loss_triplet_center","L2Loss").
    # More details see ./fastreid/modeling/meta_arch/dualtuning.py

    N2O:
      SCALE: 0.2

DATASETS:
  NAMES: ("MSMT17",)
  TESTS: ("MSMT17",)
  
OUTPUT_DIR: "logs/MSMT17/R18-softmax_n512_o512_dualtuning" 
SOLVER:
  IMS_PER_BATCH: 64
  CHECKPOINT_PERIOD: 40

TEST:
  EVAL_PERIOD: 10
  IMS_PER_BATCH: 128
