_BASE_: "../Base-bagtricks.yml"

MODEL:
  CENTERPATH: "./logs/msmt17/bagtricks_R18-softmax-part/all-center.pkl"
  BACKBONE:
    DEPTH: "18x" 
    PRETRAIN_PATH: "/home/baiyan/.cache/torch/checkpoints/resnet18-5c106cde.pth" 
    FEAT_DIM: 512 
  HEADS:
    NUM_CLASSES: 502
  LOSSES:
    NAME: ("CrossEntropyLoss",) 
  WEIGHTS: "./logs/msmt17/bagtricks_R18-softmax-part/model_final.pth"
DATASETS:
  NAMES: ("MSMT17",)
  TESTS: ("MSMT17",)

OUTPUT_DIR: "logs/msmt17/bagtricks_R18-softmax-part"

SOLVER:
  IMS_PER_BATCH: 64
  CHECKPOINT_PERIOD: 10
  MAX_EPOCH: 120
TEST:
  EVAL_PERIOD: 10
  IMS_PER_BATCH: 128
