_BASE_: "../Base-bagtricks.yml"

MODEL:
  BACKBONE:
    DEPTH: "18x"  
    PRETRAIN_PATH: "/home/baiyan/.cache/torch/checkpoints/resnet18-5c106cde.pth" 
    FEAT_DIM: 512
  HEADS:
    NUM_CLASSES: 502 
  LOSSES:
    NAME: ("CrossEntropyLoss",) 
DATASETS:
  NAMES: ("partMSMT17",)
  TESTS: ("MSMT17",)

OUTPUT_DIR: "logs/msmt17/bagtricks_R18-softmax-part"

SOLVER:
  IMS_PER_BATCH: 64
  CHECKPOINT_PERIOD: 10
  MAX_EPOCH: 120
TEST:
  EVAL_PERIOD: 120
  IMS_PER_BATCH: 128
